import Foundation
import SwiftData

/// A detected change worth the user's attention — the atom of the
/// "What Changed?" system in Section 4.
///
/// Events are generated by deterministic detectors comparing the current state
/// against a prior snapshot. They are stored rather than recomputed so the app
/// can answer "what appeared since I last opened this" and so the user can
/// scroll back through a security's history of notable changes.
@Model
final class DetectedEvent {
    var security: Security?

    var kindRaw: String
    var detectedAt: Date
    /// When the underlying change actually happened, which may be well before
    /// we noticed it.
    var occurredAt: Date

    var headline: String
    /// The objective supporting numbers, e.g. "Volume 1.9× 60-day average".
    var detailLines: [String]
    /// The "Why this matters" text from Section 4 — an explanation of the
    /// relationships between the data, never a recommendation.
    var context: String?

    /// 0–1. How unusual this is relative to the security's own history, used
    /// for the "most unusual" sort. Not a measure of importance or of
    /// direction, and explicitly not a prediction.
    var unusualness: Double

    var isAcknowledged: Bool
    /// Serialised source references so an event can always be traced back.
    var sourceDetails: [String]
    var sourceURLs: [URL]

    init(
        security: Security? = nil,
        kind: EventKind,
        detectedAt: Date = .now,
        occurredAt: Date,
        headline: String,
        detailLines: [String] = [],
        context: String? = nil,
        unusualness: Double = 0,
        isAcknowledged: Bool = false,
        sourceDetails: [String] = [],
        sourceURLs: [URL] = []
    ) {
        self.security = security
        self.kindRaw = kind.rawValue
        self.detectedAt = detectedAt
        self.occurredAt = occurredAt
        self.headline = headline
        self.detailLines = detailLines
        self.context = context
        self.unusualness = unusualness
        self.isAcknowledged = isAcknowledged
        self.sourceDetails = sourceDetails
        self.sourceURLs = sourceURLs
    }

    var kind: EventKind { EventKind(rawValue: kindRaw) ?? .other }
}

/// The change types from Section 4.
enum EventKind: String, Codable, Sendable, CaseIterable {
    case unusualPriceMove
    case unusualVolume
    case volatilityShift
    case analystEstimateRevision
    case priceTargetChange
    case ratingChange
    case earningsSurprise
    case insiderTransaction
    case newFiling
    case fundamentalShift
    case marginChange
    case revenueGrowthChange
    case freeCashFlowChange
    case debtChange
    case valuationChange
    case sectorRelativeMove
    case marketRelativeMove
    case majorNews
    case other

    var displayName: String {
        switch self {
        case .unusualPriceMove: "Unusual price move"
        case .unusualVolume: "Unusual volume"
        case .volatilityShift: "Volatility shift"
        case .analystEstimateRevision: "Estimate revision"
        case .priceTargetChange: "Price target change"
        case .ratingChange: "Rating change"
        case .earningsSurprise: "Earnings surprise"
        case .insiderTransaction: "Insider transaction"
        case .newFiling: "New filing"
        case .fundamentalShift: "Fundamental change"
        case .marginChange: "Margin change"
        case .revenueGrowthChange: "Revenue growth change"
        case .freeCashFlowChange: "Free cash flow change"
        case .debtChange: "Debt change"
        case .valuationChange: "Valuation change"
        case .sectorRelativeMove: "Sector-relative move"
        case .marketRelativeMove: "Market-relative move"
        case .majorNews: "News"
        case .other: "Other"
        }
    }

    var systemImage: String {
        switch self {
        case .unusualPriceMove, .marketRelativeMove, .sectorRelativeMove: "arrow.up.arrow.down"
        case .unusualVolume: "chart.bar"
        case .volatilityShift: "waveform.path.ecg"
        case .analystEstimateRevision, .priceTargetChange, .ratingChange: "pencil.line"
        case .earningsSurprise: "exclamationmark.bubble"
        case .insiderTransaction: "person.badge.key"
        case .newFiling: "doc.text"
        case .fundamentalShift, .marginChange, .revenueGrowthChange,
             .freeCashFlowChange, .debtChange: "building.columns"
        case .valuationChange: "tag"
        case .majorNews: "newspaper"
        case .other: "circle"
        }
    }

    /// Which of the Section 12 evidence buckets this belongs to.
    var evidenceCategory: EvidenceCategory {
        switch self {
        case .unusualPriceMove, .unusualVolume, .volatilityShift: .marketStructure
        case .sectorRelativeMove: .industry
        case .marketRelativeMove: .marketWide
        default: .companySpecific
        }
    }
}

/// The evidence organisation from Section 12.
enum EvidenceCategory: String, Sendable, CaseIterable, Identifiable {
    case companySpecific
    case industry
    case macroeconomic
    case marketWide
    case marketStructure

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .companySpecific: "Company-specific"
        case .industry: "Industry"
        case .macroeconomic: "Macroeconomic"
        case .marketWide: "Market-wide"
        case .marketStructure: "Market structure"
        }
    }
}
