plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKmpLibrary)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.room)
}

/**
 * Turns `commonTest/resources/fixtures` into a Kotlin source file.
 *
 * Kotlin Multiplatform has no common way to read a resource from a test
 * binary: the JVM wants the classpath, Kotlin/Native wants a bundle that the
 * test runner does not build. Generating the payloads as source sidesteps the
 * whole problem, and the fixture files stay on disk as ordinary readable JSON
 * rather than being pasted into a test.
 *
 * Literals are chunked because a JVM string constant cannot exceed 64 KB in
 * the class file, and `sec_companyfacts_AAPL.json` is 140 KB.
 */
val generateFixtures = tasks.register("generateFixtures") {
    val source = layout.projectDirectory.dir("src/commonTest/resources/fixtures")
    val output = layout.buildDirectory.dir("generated/fixtures/kotlin")
    inputs.dir(source)
    outputs.dir(output)

    doLast {
        val target = output.get().asFile.resolve("com/tylerabitbol/libra/fixtures")
        target.deleteRecursively()
        target.mkdirs()

        val files = source.asFile.listFiles().orEmpty().filter { it.isFile }.sortedBy { it.name }
        val builder = StringBuilder()
        builder.appendLine("package com.tylerabitbol.libra.fixtures")
        builder.appendLine()
        builder.appendLine("// Generated by the `generateFixtures` Gradle task. Do not edit.")
        builder.appendLine("// Source: core/src/commonTest/resources/fixtures")
        builder.appendLine()
        builder.appendLine("internal val fixtureContents: Map<String, String> = mapOf(")
        for (file in files) {
            val chunks = file.readText().chunked(20_000)
            builder.appendLine("    \"" + file.name + "\" to listOf(")
            for (chunk in chunks) {
                builder.append("        \"")
                builder.append(
                    chunk
                        .replace("\\", "\\\\")
                        .replace("\"", "\\\"")
                        .replace("${'$'}", "\\${'$'}")
                        .replace("\n", "\\n")
                        .replace("\r", "\\r")
                        .replace("\t", "\\t"),
                )
                builder.appendLine("\",")
            }
            builder.appendLine("    ).joinToString(\"\"),")
        }
        builder.appendLine(")")
        target.resolve("FixtureContents.kt").writeText(builder.toString())
    }
}

kotlin {
    // Room's generated `LibraDatabaseConstructor` is an `actual object`, which
    // the compiler still reports as beta. The pattern is Room's, not ours, and
    // there is no alternative spelling.
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    jvmToolchain(libs.versions.jvmToolchain.get().toInt())

    android {
        namespace = "com.tylerabitbol.libra.core"
        compileSdk = libs.versions.androidCompileSdk.get().toInt()
        minSdk = libs.versions.androidMinSdk.get().toInt()

        // `KeystoreSecretsStore` needs a real AndroidKeyStore, which exists
        // only on a device or emulator. This is the only compilation in the
        // project that can exercise it; everything else about secrets is
        // covered by the common tests on JVM and the iOS simulator.
        withDeviceTest {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        }
    }

    // Exists only so commonTest runs fast: ./gradlew :core:jvmTest
    jvm()
    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain.dependencies {
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kermit)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.ktor.client.encoding)
            implementation(libs.room.runtime)
            implementation(libs.sqlite.bundled)
        }
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
        }
        jvmMain.dependencies {
            implementation(libs.ktor.client.okhttp)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        commonTest {
            kotlin.srcDir(generateFixtures)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
        // `getByName`, not the `androidDeviceTest` accessor: `withDeviceTest`
        // creates the source set during configuration, and the typed accessors
        // are generated from the *previous* configuration, so a clean checkout
        // would fail to compile this script.
        getByName("androidDeviceTest").dependencies {
            implementation(kotlin("test"))
            implementation(libs.androidx.test.runner)
            implementation(libs.androidx.test.core)
            implementation(libs.androidx.test.ext.junit)
        }
    }
}

// `"${'$'}projectDir/schemas"` escapes the dollar, so Room was handed the literal
// string and exported into a directory named `$projectDir`. Resolve the path
// here instead, where there is nothing to escape.
room {
    schemaDirectory(layout.projectDirectory.dir("schemas").asFile.path)
}

// Room's compiler runs through KSP, which must be wired up per target rather
// than once: there is no `ksp(...)` shorthand in a multiplatform build.
dependencies {
    add("kspAndroid", libs.room.compiler)
    add("kspJvm", libs.room.compiler)
    add("kspIosArm64", libs.room.compiler)
    add("kspIosSimulatorArm64", libs.room.compiler)
}
